export const environment = {
  production: false,
  apiKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTM0OTMyYi1kNTVmLTRlMDktOGI0OC1lZjQ3ZmUxOTA1ZjgiLCJlbWFpbCI6ImthdGVAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkthdGUiLCJuYmYiOjE2OTcyOTE0NTcsImV4cCI6MTY5NzMyMDI1NywiaWF0IjoxNjk3MjkxNDU3LCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.x2LIOeCgfnDvRq3SlFxtzBCL9Cv1pKVWNNGStoUfv8o',
};
